version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: security25db
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: security25-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: security25db
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: adminpass
    depends_on:
      - mongodb
    networks:
      - app-network
volumes:
  mongodb_data:
networks:
  app-network:
    driver: bridge