apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aitest-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/C0ldarm/Story_begin.git
    targetRevision: helm-deploy
    path: Labs/DevOpsLabs/Lab-2/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true