apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aitest
  template:
    metadata:
      labels:
        app: aitest
    spec:
      containers:
      - name: aitest
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: "{{ .Values.mongodb.auth.database }}"
        - name: SPRING_DATA_MONGODB_USERNAME
          value: "root"                                      # ← root замість admin
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: "{{ .Values.mongodb.auth.rootPassword }}"   # ← rootPassword
        - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
          value: "admin"