apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aitest-monitor
  labels:
    release: prometheus      
spec:
  selector:
    matchLabels:
      app: aitest
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s